name: Auto merge version
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release from tag
        uses: caijinglong/action-version-merge
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
